version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "8000:8000"
    networks:
      - my-network

  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
